### ISSUE TITLE
Off-by-one in input validation

### ISSUE THREAD

**Issue by nixberg** [jedisct1/rust-xoodyak#1]
https://github.com/jedisct1/rust-xoodyak/blob/e8c6babb1477ea3ee6ac97b29562715b9c190bb6/src/xoodyak/mod.rs#L105

[Quoting the specification](https://csrc.nist.gov/CSRC/media/Projects/lightweight-cryptography/documents/round-2/spec-doc-rnd2/Xoodyak-spec-round2.pdf): ` with | K || id | ≤ R_kin − 1`.

**Comment by jedisct1** [comment]
Good catch, thanks!
