### ISSUE TITLE
Wrong test vector?

### ISSUE THREAD

**Issue by nixberg** [jedisct1/rust-xoodyak#2]
https://github.com/jedisct1/rust-xoodyak/blob/449e8e2998eb311cf93b1499ddc045f1a85bc5ab/src/test.rs#L18-L29

The hash of the empty string [should be](https://csrc.nist.gov/Projects/lightweight-cryptography/round-2-candidates#Xoodyak) `EA152F2B47BCE24EFB66C479D4ADF17BD324D806E85FF75EE369EE50DC8F8BD1` which translates to `[234, 21, 47, 43, 71, 188, 226, 78, 251, 102, 196, 121, 212, 173, 241, 123, 211, 36, 216, 6, 232, 95, 247, 94, 227, 105, 238, 80, 220, 143, 139, 209]`.

The root of this issue would be the use of `[u8].chunks(rate)` in `absorb_any` etc. instead of `Split(X, n)` as defined on page 10 of the [specification](https://csrc.nist.gov/CSRC/media/Projects/lightweight-cryptography/documents/round-2/spec-doc-rnd2/Xoodyak-spec-round2.pdf).

Note that adding `st.absorb(&[]);` to the snippet above does not change the result, but it should (pp. 8–9).

**Comment by jedisct1** [comment]
The output is matching the reference implementation from XKCP. Not sure which one is wrong, but the XKCP implementation is more recent than the document.

**Comment by jedisct1** [comment]
Ah, I see. Thanks for reporting this!

It should be fixed now.
